name: Build On Push

on:
  push:
    branches: [ master ]

jobs:
  build_main:
    name: Build for ${{ matrix.target_branch }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        target_branch:
          - sm-latest
          - sm-1.11
        include:
          - dbg_ext: pdb

          - target_branch: sm-latest
            mm_branch: "master"
            sm_branch: "master"

          - target_branch: sm-1.11
            mm_branch: "1.11-dev"
            sm_branch: "1.11-dev"

    steps:
    - name: Add msbuild to PATH (Windows)
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Install (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        :: See https://github.com/microsoft/vswhere/wiki/Find-VC
        for /f "usebackq delims=*" %%i in (`vswhere -latest -property installationPath`) do (
          call "%%i"\Common7\Tools\vsdevcmd.bat -arch=x86 -host_arch=x64
        )
        
        :: Loop over all environment variables and make them global.
        for /f "delims== tokens=1,2" %%a in ('set') do (
          echo>>"%GITHUB_ENV%" %%a=%%b
        )
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Setup ambuild
      run: |
        python -m pip install wheel
        pip install git+https://github.com/alliedmodders/ambuild
    - name: Fetch Metamod:Source ${{ matrix.mm_branch }}
      uses: actions/checkout@v3
      with:
        repository: alliedmodders/metamod-source
        ref: ${{ matrix.mm_branch }}
        path: mmsource

    - name: Fetch SourceMod ${{ matrix.sm_branch }}
      uses: actions/checkout@v3
      with:
        repository: alliedmodders/sourcemod
        ref: ${{ matrix.sm_branch }}
        path: sourcemod
        submodules: recursive

    - name: Fetch Source SDKs
      shell: bash
      run: |
        git clone --mirror https://github.com/alliedmodders/hl2sdk hl2sdk-proxy-repo
        sdks=(tf2)
        for sdk in "${sdks[@]}"
        do
          git clone hl2sdk-proxy-repo -b $sdk hl2sdk-$sdk
        done

    - name: Fetch PathFollower
      uses: actions/checkout@v3
      with:
        path: pathfollower

    - name: Build Files
      working-directory: pathfollower
      run: |
        mkdir post
        cd post
        python3 ../configure.py --enable-optimize --sdks=present --sm-path="${{ github.workspace }}/sourcemod" --mms-path="${{ github.workspace }}/mmsource"
        ambuild

    - name: Get Short SHA
      uses: benjlevesque/short-sha@v2.1
      id: short-sha

    - name: Upload Artifact for ${{ matrix.target_branch }}
      uses: actions/upload-artifact@v3
      with:
        name: pathfollower-${{ runner.target_branch }}-${{ steps.short-sha.outputs.sha }}
        path: |
            pathfollower/post/package/*

    - name: Upload Debug Symbols for ${{ matrix.target_branch }}
      uses: actions/upload-artifact@v3
      with:
        name: pathfollower-dbgsym-${{ runner.target_branch }}-${{ steps.short-sha.outputs.sha }}
        path: |
            pathfollower/post/**/*.${{ matrix.dbg_ext }}